-- Maak database aan
CREATE DATABASE [$(dbname)]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'$(dbname)', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\$(dbname).mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'$(dbname)_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\$(dbname)_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [$(dbname)] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [$(dbname)] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [$(dbname)] SET ANSI_NULLS OFF
GO
ALTER DATABASE [$(dbname)] SET ANSI_PADDING OFF
GO
ALTER DATABASE [$(dbname)] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [$(dbname)] SET ARITHABORT OFF
GO
ALTER DATABASE [$(dbname)] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [$(dbname)] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [$(dbname)] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [$(dbname)] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [$(dbname)] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [$(dbname)] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [$(dbname)] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [$(dbname)] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [$(dbname)] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [$(dbname)] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [$(dbname)] SET  DISABLE_BROKER
GO
ALTER DATABASE [$(dbname)] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [$(dbname)] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [$(dbname)] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [$(dbname)] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [$(dbname)] SET  READ_WRITE
GO
ALTER DATABASE [$(dbname)] SET RECOVERY FULL
GO
ALTER DATABASE [$(dbname)] SET  MULTI_USER
GO
ALTER DATABASE [$(dbname)] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [$(dbname)] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [$(dbname)] SET DELAYED_DURABILITY = DISABLED
GO
USE [$(dbname)]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [$(dbname)]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [$(dbname)] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

-- Maak user aan
USE [master]
GO
CREATE LOGIN [$(login)] WITH PASSWORD=N'$(password)', DEFAULT_DATABASE=[$(dbname)], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [$(dbname)]
GO
CREATE USER [$(login)] FOR LOGIN [$(login)]
GO
USE [$(dbname)]
GO
ALTER ROLE [db_datareader] ADD MEMBER [$(login)]
GO
USE [$(dbname)]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [$(login)]
GO
USE [$(dbname)]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [$(login)]
GO